apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
        - name: pi
          env:
            - name: username
              valueFrom:
                configMapKeyRef:
                  name: argocd-sync-user-dev # The ConfigMap this value comes from.
                  key: argo_cd_sync_user # The key to fetch.
            - name: sync_start_time
              valueFrom:
                configMapKeyRef:
                  name: argocd-sync-user-dev
                  key: argo_cd_sync_user_timestamp
            - name: git_ref
              valueFrom:
                configMapKeyRef:
                  name: argocd-sync-user-dev
                  key: argo_cd_sync_user_git_ref
          image: perl:5.34.0
          command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000) && print $ENV{username}"]
      restartPolicy: Never
  backoffLimit: 4
